baseurl      = "https://akrisanov.com/"
languageCode = "en-US"
title        = "Andrey Krisanov - Yet Another Software Engineer Notes"
paginate     = 10

theme            = "after-dark"
enableRobotsTXT  = true
googleAnalytics  = "UA-58969714-1"
disqusShortname  = "akrisanov"

related_content_limit      = 3
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

pygmentsuseclasses = true
pygmentsstyle      = "xcode"

[params]
  description   = """Hi! My name is Andrey Krisanov. I'm Software engineer with several years of
                     experience in full-stack application development, DevOps, and team management.
                     I write this blog in English and Russian about things that I'm interested in:
                     programming languages, distributed systems, data engineering, IT industry
                     and startups."""
  author        = "Andrey Krisanov" # Optional, controls author name display on posts
  hide_author   = true              # Optional, set true to hide author name on posts
  show_menu     = true              # Optional, set true to enable section menu
  powered_by    = true              # Optional, set false to disable credits
  images        = []                # Suggested, adds default OpenGraph image
  theme_variant = "standard"

[params.seo.webmaster_verifications]
  google = "EciQ4PNrvJi6zwm0o058Y6ERxdF1pcUPQEidccORsLI" # Optional, Google verification code
  bing   = "88ED584660D28721AA9E00590ABA227F"            # Optional, Bing verification code
  yandex = "d5325e91836a5569"                            # Optional, Yandex verification code
  alexa  = ""                                            # Optional, Alexa verification code

[[menu.main]]
  name       = "Home"
  weight     = 1
  identifier = "home"
  url        = "/"
