baseurl      = "https://akrisanov.com/"
languageCode = "en-US"
title        = "Software Engineer (Go, JavaScript, Clojure, Ruby)"
paginate     = 5

theme            = "after-dark"
enableRobotsTXT  = true
googleAnalytics  = "UA-58969714-1"
disqusShortname  = "akrisanov"

related_content_limit      = 3
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

PygmentsCodeFences = true

[params]
  description   = """I work with Go, JavaScript, Clojure and Ruby.
                     Interested in functional programming, distributed systems, and machine learning."""
  author        = "Andrey Krisanov" # Optional, controls author name display on posts
  hide_author   = true              # Optional, set true to hide author name on posts
  show_menu     = true              # Optional, set true to enable section menu
  powered_by    = true              # Optional, set false to disable credits
  images        = []                # Suggested, adds default OpenGraph image
  theme_variant = "standard dark-grey"

[params.seo.webmaster_verifications]
  google = "EciQ4PNrvJi6zwm0o058Y6ERxdF1pcUPQEidccORsLI" # Optional, Google verification code
  bing   = "88ED584660D28721AA9E00590ABA227F"            # Optional, Bing verification code
  yandex = "d5325e91836a5569"                            # Optional, Yandex verification code
  alexa  = ""                                            # Optional, Alexa verification code

[[menu.main]]
  name       = "Home"
  weight     = 1
  identifier = "home"
  url        = "/"
[[menu.main]]
  name       = "About"
  weight     = 2
  identifier = "about"
  url        = "/about/"
[[menu.main]]
  name       = "CV (Resume)"
  weight     = 3
  identifier = "cv"
  url        = "/cv/"
