baseurl      = "https://akrisanov.com/"
languageCode = "en-US"
title        = "Software Engineer (JavaScript, React, Node.js, Ruby, .NET Core)"
paginate     = 5

theme            = "after-dark"
enableRobotsTXT  = true
googleAnalytics  = "UA-58969714-1"
disqusShortname  = "akrisanov"

related_content_limit      = 3
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = """I work mostly on backends in Ruby, Node.js, .NET Core.
                   Have fun with JavaScript / TypeScript, React, React Native, F#.
                   Can design, implement and maintain product infrastructure running on AWS.
                   Interested in distributed systems, and machine learning."""
  author      = "Andrey Krisanov" # Optional, controls author name display on posts
  hide_author = true              # Optional, set true to hide author name on posts
  show_menu   = true              # Optional, set true to enable section menu
  powered_by  = true              # Optional, set false to disable credits
  images      = []                # Suggested, adds default OpenGraph image

[params.seo.webmaster_verifications]
  google = "EciQ4PNrvJi6zwm0o058Y6ERxdF1pcUPQEidccORsLI" # Optional, Google verification code
  bing   = "88ED584660D28721AA9E00590ABA227F"            # Optional, Bing verification code
  yandex = "d5325e91836a5569"                            # Optional, Yandex verification code
  alexa  = ""                                            # Optional, Alexa verification code

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    identifier = "post"
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 3