baseurl      = "https://akrisanov.com/"
languageCode = "en-US"
title        = "Software Engineer (Go, JavaScript, Ruby)"
paginate     = 5

theme            = "after-dark"
enableRobotsTXT  = true
googleAnalytics  = "UA-58969714-1"
disqusShortname  = "akrisanov"
toc              = true
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

related_content_limit      = 3
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = """Work mostly on backends in Go, Node.js and Ruby.
                   Having fun with JavaScript (God bless ES6/7), Node.js, React, React Native, PWA.
                   Interested in functional programming, large scale distributed systems,
                   big data and machine learning."""
  author      = "Andrey Krisanov" # Optional, controls author name display on posts
  hide_author = true              # Optional, set true to hide author name on posts
  show_menu   = false             # Optional, set true to enable section menu
  powered_by  = true              # Optional, set false to disable credits
  images      = []                # Suggested, adds default OpenGraph image

[params.seo.webmaster_verifications]
  google = "" # Optional, Google verification code
  bing   = "" # Optional, Bing verification code
  alexa  = "" # Optional, Alexa verification code
  yandex = "" # Optional, Yandex verification code